name: "Publish to GHCR and Sign"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true 

runs:
  using: "composite"
  steps:
      - name: Checking out!
        uses: actions/checkout@v3
  
      - name: Install Oras
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_amd64.tar.gz
          mkdir -p oras-install/
          tar -zxf oras_0.12.0_*.tar.gz -C oras-install/
          mv oras-install/oras /usr/local/bin/
          rm -rf oras_0.12.0_*.tar.gz oras-install/
          echo "Oras installed!"
        shell: bash
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.8.0' # optional
          
      - name: Package Action
        uses: ruchika-jain/package-action@1.0.1

      - name: Echo 
        run: |
            echo "This is after the package action step"
        shell: bash
      
      - name: Sign package
        uses: ruchika-jain/sign-package@1.0.1
        
      
